application: mol-lab
version: canary
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /admin/.*
  script: app.py
  login: admin

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /cache/sql/.*
  script: sql_cache_handler.py

- url: /cache/tile/.*
  script: tile_cache_handler.py

- url: /.*
  script: app.py
