application: mol-lab
version: points
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

inbound_services:
- channel_presence

handlers:

- url: /earthengine(/.*)?
  script: frontend.py

- url: /js
  static_dir: js
